version: "3.9"
services:
  moveit2:
    image: moveit2-sim
    container_name: moveit2_sim
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./src:/root/ws_moveit2/src
    command: bash
    network_mode: host
